global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_conf.yaml"
    watch: true
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /var/traefik/certs/rafaelhome.mourou.gr.pem
        keyFile: /var/traefik/certs/rafaelhome.mourou.gr.key.pem
  options:
    myTLSOptions:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13